-- Seed data for National Infotech College Portal
USE nic_portal;

-- Insert default users (passwords are hashed: Admin@123, Faculty@123, Student@123)
-- Hash: $2b$10$rQZ9vXqZ9vXqZ9vXqZ9vXuO (placeholder - will be generated by backend)
INSERT INTO users (email, password, role) VALUES
('admin@nic.edu.np', '$2b$10$YourHashedPasswordHere', 'admin'),
('faculty@nic.edu.np', '$2b$10$YourHashedPasswordHere', 'faculty'),
('student@nic.edu.np', '$2b$10$YourHashedPasswordHere', 'student');

-- Insert sample faculty
INSERT INTO faculty (user_id, faculty_id, first_name, last_name, phone, department, specialization) VALUES
(2, 'FAC001', 'Rajesh', 'Sharma', '9841234567', 'Computer Science', 'Data Structures');

-- Insert sample student
INSERT INTO students (user_id, student_id, first_name, last_name, phone, address, program, semester, enrollment_date) VALUES
(3, 'STU001', 'Sita', 'Thapa', '9851234567', 'Birgunj-10', 'BCA', 1, '2024-01-15');

-- Insert courses for +2 Science
INSERT INTO courses (code, name, program, semester, credits, description) VALUES
('PHY101', 'Physics I', '+2 Science', 1, 4, 'Mechanics and Thermodynamics'),
('CHEM101', 'Chemistry I', '+2 Science', 1, 4, 'Physical and Inorganic Chemistry'),
('MATH101', 'Mathematics I', '+2 Science', 1, 5, 'Calculus and Algebra'),
('BIO101', 'Biology I', '+2 Science', 1, 4, 'Cell Biology and Genetics');

-- Insert courses for BCA
INSERT INTO courses (code, name, program, semester, credits, description) VALUES
('BCA101', 'Computer Fundamentals', 'BCA', 1, 3, 'Introduction to Computing'),
('BCA102', 'C Programming', 'BCA', 1, 4, 'Programming in C Language'),
('BCA103', 'Digital Logic', 'BCA', 1, 3, 'Logic Gates and Circuits'),
('BCA104', 'Mathematics I', 'BCA', 1, 4, 'Discrete Mathematics');

-- Insert courses for B.Sc CSIT
INSERT INTO courses (code, name, program, semester, credits, description) VALUES
('CSC101', 'Introduction to IT', 'B.Sc CSIT', 1, 3, 'IT Fundamentals'),
('CSC102', 'C Programming', 'B.Sc CSIT', 1, 3, 'Programming in C'),
('CSC103', 'Digital Logic', 'B.Sc CSIT', 1, 3, 'Digital Systems'),
('CSC104', 'Mathematics I', 'B.Sc CSIT', 1, 3, 'Calculus and Algebra');

-- Assign subjects to faculty
INSERT INTO subjects (course_id, faculty_id, academic_year) VALUES
(6, 1, '2024'),
(7, 1, '2024');

-- Enroll student in subjects
INSERT INTO enrollments (student_id, subject_id, enrollment_date) VALUES
(1, 1, '2024-01-15'),
(1, 2, '2024-01-15');

-- Sample attendance records
INSERT INTO attendance (student_id, subject_id, date, status, marked_by) VALUES
(1, 1, '2024-01-20', 'present', 1),
(1, 1, '2024-01-21', 'present', 1),
(1, 1, '2024-01-22', 'absent', 1),
(1, 2, '2024-01-20', 'present', 1);

-- Sample results
INSERT INTO results (student_id, subject_id, exam_type, exam_date, marks_obtained, total_marks, uploaded_by) VALUES
(1, 1, 'weekly_test', '2024-01-25', 18, 20, 1),
(1, 2, 'weekly_test', '2024-01-26', 16, 20, 1);

-- Sample notifications
INSERT INTO notifications (title, message, type, target_role, created_by) VALUES
('Welcome to NIC Portal', 'Welcome to National Infotech College Student Portal', 'announcement', 'all', 1),
('Weekly Test Schedule', 'Weekly tests will be conducted every Friday', 'test', 'student', 1);
